[package]
name = "hashwires"
version = "0.0.1"
authors = ["Yolan Romailler <yromailler@fb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.0"
hex = "0.4.2"